### ISSUE TITLE
[新功能建议]建议新增调整UI显示位置的配置

### ISSUE THREAD

**Issue by ChenXu233** [Nova-Committee/BoatOverhaul#1]
因为我想在同时获得过肩膀视角和这个行船玩法,但是这个玩法的UI挡住了玩家(很难受

![image](https://user-images.githubusercontent.com/91937041/213621617-6dac4f8a-d2a2-401c-9955-0eca4c54ac18.png)

过肩视角可以调整过肩的位移,但是把玩家调到右边比较难受(习惯了左边)

![image](https://user-images.githubusercontent.com/91937041/213621492-13de3ce1-f5cb-43e7-97e7-0b40c8d0e0b2.png)

所以建议在配置文件里面新增一个调整UI显示位置的设置(

**Comment by VulpesStella** [comment]
开发时甚至给位置调整预留了四个变量，你不说我都忘了（

**Comment by ChenXu233** [comment]
还有一个比较难受的地方就是,手动挂挡下面左右移动的挂挡三角形指标要移动超过指示的挂挡的一半才会开始转弯,这时候放开挂挡回弹在还没弹回0挡位的时候还是会继续这个挡位的转弯,这导致难以微操(当然我没玩过战舰世界,如果是战舰世界本来就有的设定,我就没什么意见了)

**Comment by VulpesStella** [comment]
确实是战舰世界的设定
微操也可以实现，之后可以加入多个隐藏的小档位，这样手动控制时就能小舵转弯了

**Comment by ChenXu233** [comment]
期待之后的版本
![3Z(WB5}$A4) 2%A~)`SLU77](https://user-images.githubusercontent.com/91937041/213693169-0bc2b797-bad3-423b-9c0d-58b414b9e52b.jpg)

**Comment by VulpesStella** [comment]
你的minecraft版本是？我优先把这个版本的更新做了

**Comment by ChenXu233** [comment]
1.19.2 fabric

**Comment by VulpesStella** [comment]
试试 https://github.com/Nova-Committee/BoatOverhaul/releases/tag/2.0.0-dev

**Comment by VulpesStella** [comment]
更新之前先把配置文件删除，方便重新生成
